### ISSUE TITLE
Endpoint for storing json token metadata on ipfs

### ISSUE THREAD

**Issue by bhaskarSingh** [buidl-labs/cryptoverse-wars-backend#5]
JSON object should have the following values.

```javascript
{
"name": "3D Cryptobot",
"symbol": "CB",
"decimals": 0,
"description": "Custom made NFT 3d cryptobot",
"isBooleanAmount": true,
"isTransferable": true,
"shouldPreferSymbol": false,
"language": "en",
"tags": ["3D model", "Collectables", "NFT", "Cryptobot"],
"attributes": [  {
    "color_schema": {"": ""},
    "body_parts_type": {"": ""} 
  }  ], 
"externalUri": "https://cryptocodeschool.in/tezos/",
"artifactUri": "<insert-3d-model-ipfs-url-here>",
"displayUri": "<insert-3d-model-ipfs-image-url-here>"
}
```

**Comment by manangouhari** [comment]
Shouldn't external URI be - `"https://cryptocodeschool.in/tezos/<cryptobot_id>"`?

**Comment by manangouhari** [comment]
Draft PR raised here - #6

**Comment by bhaskarSingh** [comment]
> Shouldn't external URI be - "https://cryptocodeschool.in/tezos/<cryptobot_id>"?

Makes sense. eg: https://develop.cryptocodeschool.in/tezos/cryptobot/1614857111682

It's best to use a service like bitly here so that incase in future URL changes. We can redirect users to a diff url.

**Comment by manangouhari** [comment]
> It's best to use a service like bitly here so that incase in future URL changes. We can redirect users to a diff url.

So, what's the verdict? How should I go about this?

**Comment by bhaskarSingh** [comment]
> So, what's the verdict? How should I go about this?

Let's keep it simple. Using the landing page URL is enough "https://cryptocodeschool.in/tezos/".

Also, add an additional key-value pair for `tokenId: <bot-token-id>`
